store-message is working
BharatShukla30/neighborly-node-chat pull request #18
Opened 2024-08-03 16:56 UTC by KUSHAL-OMER

2024-08-03 22:14 UTC, BharatShukla30 requested changes

2024-08-03 22:14 UTC, BharatShukla30 commented on node-backend/controllers/chatController.js
> +  formData.append("file", msg.mediaLink);
Make sure we send the file here

2024-08-03 22:14 UTC, BharatShukla30 commented on node-backend/controllers/chatController.js
> +  await fetch("http://localhost:5000/group/store-message", {
Put this url in constants as it will change in prod

2024-08-03 22:14 UTC, BharatShukla30 commented on node-backend/controllers/chatController.js
> +  console.log(typeof msg.mediaLink);
Remove console statement

2024-08-05 04:27 UTC, KUSHAL-OMER commented on node-backend/controllers/chatController.js
> +  formData.append("file", msg.mediaLink);
I saw in the frontend from there the file is coming with the field name medialink

2024-08-05 16:34 UTC, merged